### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by nicola** [rdf-ext/rdf-parser-n3#4]
```
N3Parser.prototype.process = function (data, callback, base, filter, done) {
```

What if I don't pass the callback ?

**Comment by bergos** [comment]
@nicola I expect an error will be thrown. But way do you want to call that method without callback? The purpose of the method is to process every single triple separate. I don't see a use case were it would make sense to call the method without callback.

**Comment by nicola** [comment]
@bergos sorry, I had misunderstood the purpose of this function
